config/routes.rb
Rails.application.routes.draw do
  resources :arts

  resources :profiles

  resources :comments

  root "arts#index"
  devise_for :users
  get "links/mine", to: "links#mine"
  get "users/profile/:id", to: "users#user_profile"
  get "artists", to: "profiles#index"
  resources :links do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end

end

app/models/art.rb
class Art < ActiveRecord::Base
  belongs_to :user

  has_attached_file :artwork, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :artwork, :content_type => /\Aimage\/.*\Z/
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
require 'uri'

class Link < ActiveRecord::Base
  validates_format_of :url, :with => URI.regexp(['http', 'https'])
  acts_as_votable
  belongs_to :user
  has_many :comments
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
  has_many :art
  has_one :profile
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  layout 'yeti'
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :avatar
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :avatar
  end

end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: [:show, :edit, :update, :destroy]
  before_action :authorized_user, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]

  respond_to :html

  def index
    @arts = Art.take(20) # random 20 artwork
    @latests = Art.order('updated_at DESC')
    @artists = Profile.take(20) # random 20 artist
    respond_with(@arts)
  end

  def show
    @other_works = @art.user.art
    respond_with(@art)
  end

  def new
    @art = Art.new
    respond_with(@art)
  end

  def edit
  end

  def create
    @art = Art.new(art_params)
    @art.user = current_user
    @art.save
    respond_with(@art)
  end

  def update
    @art.update(art_params)
    respond_with(@art)
  end

  def destroy
    @art.destroy
    respond_with(@art)
  end

  def authorized_user
    @art = current_user.art.find_by(id: params[:id])
    redirect_to arts_path, notice: "Not authorized to edit this link" if @art.nil?
  end


  private
    def set_art
      @art = Art.find(params[:id])
    end

    def art_params
      params.require(:art).permit(:title, :description, :image, :artwork)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  respond_to :html

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authorized_user, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /links
  # GET /links.json
  def index
    @links = Link.order('updated_at DESC')
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to :back
  end

  def mine
    @links = current_user.links
    @user = current_user
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def authorized_user
    @link = current_user.links.find_by(id: params[:id])
    redirect_to links_path, notice: "Not authorized to edit this link" if @link.nil?
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url) if !params[:link][:title].empty? and !params[:link][:url].empty?
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]

  respond_to :html

  def index
    @profiles = Profile.all
    respond_with(@profiles)
  end

  def show
    @artwork = @profile.user.art
    respond_with(@profile)
  end

  def new
    @profile = Profile.new
    respond_with(@profile)
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    @profile.save
    respond_with(@profile)
  end

  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    # @profile.destroy
    # respond_with(@profile)
    redirect_to profiles_path, notice: "Not authorized to edit this profile" 
  end

  def authorized_user
    redirect_to profiles_path, notice: "Not authorized to edit this profile" if @profile.nil?
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:name, :bio, :contact)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def user_profile
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/arts/_form.html.erb
<%= form_for(@art) do |f| %>
  <% if @art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% @art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :required => true, :placeholder => "Artwork title", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :required => true, :placeholder => "Artwork description", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :artwork %><br>
    <%= f.file_field :artwork %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to 'Cancel', arts_path, class:"btn btn-danger" %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing Art</h1>

<%= render 'form' %>

<%= link_to 'Show', @art %> |
<%= link_to 'Back', arts_path %>

app/views/arts/index.html.erb
<p id="notice"><%= notice %></p>
<p>
<div class="row clearfix">
    <!-- Put the curated arts here -->
    <% @arts.each do |art| %>
        
      <div class="col-sm-6 col-md-3">
         <div class="thumbnail">
            <%= link_to (image_tag art.artwork.url(:medium)), art  %>
         </div>
      </div>
    <% end %>
</div>

<h2>Latest Submission</h2>
<div class="row clearfix">
    <% @latests.each do |latest| %>
        
      <div class="col-md-1">
         <div class="span">
            <%= link_to (image_tag latest.artwork.url(:thumb)), latest  %>
         </div>
      </div>
    <% end %>

</div>

<h2>Artists</h2>
<div class="row clearfix">
    <% @artists.each do |artist| %>
        
      <div class="col-md-1">
         <div class="span">
            <%= link_to (image_tag artist.user.avatar.url(:thumb)), artist  %>
         </div>
      </div>
    <% end %>

</div>

app/views/arts/new.html.erb
<h1>New Art</h1>

<%= render 'form' %>

app/views/arts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row clearfix">
      <div class="col-md-4">
         <div class="span3">
            <%= image_tag @art.artwork.url(:medium) %>
         </div>
      </div> 
      <div class="col-md-8">
         <div class="span3">
           <p>
           Artwork Title: <%= @art.title %>
           </p>
          
           <p>
           Artist: <%= link_to @art.user.profile.name, @art.user.profile  %>
           </p>

           <p>
           <%= @art.description  %>
           </p>
         </div>
      </div> 

</div>
<h2>Other Works</h2>
<div class="row clearfix">
    <% @other_works.each do |a| %>
      <div class="col-md-1">
         <div class="span">
            <%= link_to (image_tag a.artwork.url(:thumb)), a  %>
         </div>
      </div>
    <% end %>
</div>

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
  <div class="comments_wrapper clearfix">
    <div class="pull-left">
      <p class="lead"><%= comment.body %></p>
      <p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.name %></small></p>
    </div>
    <div class="btn-group pull-right">
      <% if comment.user == current_user -%>
        <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link_id %><br>
    <%= f.number_field :link_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :required => true %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user.name %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>KMPLR - Dump your link here</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="logo" href="<%= root_url %>"><span>KMPLR</span></a>
      <a class="navbar-brand" id="subkmplr" href="<%= new_link_path %>"><span>SUBMIT</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" id="menukmplr">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
<% if user_signed_in? -%>
            <li><%= link_to 'Submit Link', new_link_path %> </li>
            <li><%= link_to 'My Links', links_mine_path %> </li>
            <li><%= link_to 'Account', edit_user_registration_path %> </li>
            <li><%= link_to 'Profile', edit_user_registration_path %> </li>
            <li class="divider"></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %> </li>
<% else -%>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li class="divider"></li>
            <li><a href="#">Help</a></li>
<% end -%>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <div id="main_content" class="container">
    <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
  <div id="content">
    <%= yield %>
  </div>
  </div>

</body>

<div id="footer" class="container">
  <nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="navbar-inner navbar-content-center">
    <p>
    <p class="col text-muted credit"> &nbsp; &copy; KMPLR, 2014</p>
  </div>
  </nav>
</div>
</html>

app/views/layouts/yeti.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "kmplr" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "yeti", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>
    <style>
      body {
        padding-top: 55px;
        padding-bottom: 55px;
      }
     
    </style>

  </head>
  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" id="logo" href="<%= root_url %>"><span>ARTSCOUT</span></a>
          <a class="navbar-brand" id="subkmplr" href="<%= new_art_path %>"><span>SUBMIT</span></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" id="menukmplr">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
<% if user_signed_in? -%>
            <li><%= link_to 'Submit Link', new_link_path %> </li>
            <li><%= link_to 'Submit Artwork', new_art_path %> </li>
            <li><%= link_to 'My Links', links_mine_path %> </li>
            <% if current_user.profile.nil? %>
            <li><%= link_to 'New Profile', new_profile_path %> </li>
            <% else -%>
            <li><%= link_to 'Profile', edit_profile_path(current_user.profile.id) %> </li>
            <% end -%>
            <li class="divider"></li>
            <li><%= link_to 'Account', edit_user_registration_path %> </li>
            <li class="divider"></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %> </li>
<% else -%>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end -%>
          </ul>
        </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    </div> <!-- /container -->

    <div class="container">
    <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

    <%= yield %>
    </div>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "yeti" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
  <hr>
<% if current_page?('/') -%>
<div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>About ArtScout</h2>
          <p>ArtScout is the new way to discover new arts, new artists. It is a platform for emerging artists to showcase their work, and a place for art seeker, professional galleries to scout new talents. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>T & C</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Getting Discovered</h2>
          <p>Getting discovered by registering and submitting your work today.</p>

<% if user_signed_in? -%>
          <p><a class="btn btn-default" href="<%= new_art_path %>" role="button">Submit Artwork &raquo;</a></p>
<% else -%>
          <p><a class="btn btn-default" href="<%= new_user_registration_path %>" role="button">Register &raquo;</a></p>
<% end -%>
        </div>
      </div>
 <% end -%>
<div id="footer" class="container">
  <nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="navbar-inner navbar-content-center">
    <p>
    <p class="col text-muted credit"> &nbsp; &copy; KMPLR, 2014</p>
  </div>
  </nav>
</div>

</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <%= f.label :title %> :
      <%= f.text_field :title, :required => true, :placeholder => "Link title", :class => "form-control" %>
  </div>
  <div class="form-group">
      <%= f.label :url %> :
      <%= f.text_field :url, :required => true, :placeholder => "The URL you want to submit", :class => "form-control" %>
      <small>Include URL scheme like 'http' or 'https'</small>
  </div>
  <div class="actions form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to 'Cancel', links_path, class:"btn btn-danger" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
 <div class="link row clearfix">
    <% @links.each do |link| %>
        <div class="row">
           <div class="col-xs-2 col-sm-1 col-md-1">
             <br>
             <div class="btn-group-vertical">
               <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
                 <span class="glyphicon glyphicon-chevron-up"></span>&nbsp;<%= link.get_upvotes.size %>
               <% end %>
               <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
                 <span class="glyphicon glyphicon-chevron-down">&nbsp;<%= link.get_downvotes.size %>
               <% end %>
               </div>
           </div>
           <div class="col-xs-10 col-sm-11 col-md-11">
             <h3> <%= link_to link.title, link %></h3>
             <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> by <%= link.user.name %></small>
             | <small class="author"><%= link.comments.count %> <%= link_to "comments", link %></small> <br>
           </div>
         </div>
    <% end %>
</div>
<br>

app/views/links/mine.html.erb
<%=
  if !@user.avatar.url.nil?
      image_tag @user.avatar.url(:thumb), class:"img-circle"
    end 
%>

<div class="link row clearfix">
    <% @links.each do |link| %>
         <h2> <%= link_to link.title, link %></h2>
         <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> by <%= link.user.name %></small> <br>
    <div class="btn-group">
      <a class="btn btn-default btn-sm" href="<%= link.url %>">Visit</a>
      <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Upvote
        <%= link.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down">
        Downvote
        <%= link.get_downvotes.size %>
      <% end %>
      <%= link_to 'Edit', edit_link_path(link), class: "btn btn-default btn-sm" %>
      <%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm"  %>
    </div>
    <% end %>
</div>
<br>

app/views/links/new.html.erb
<h1>Submit new link</h1>

<%= render 'form' %>

</div>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>
    <div class="btn-group">
      <a class="btn btn-default btn-sm" href="<%= @link.url %>">Visit Link</a>
      <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Upvote
        <%= @link.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down">
        Downvote
        <%= @link.get_downvotes.size %>
      <% end %>
      <%= link_to 'Edit', edit_link_path(@link), class: "btn btn-default btn-sm" %> 
      <%= link_to 'Back', links_path, class: "btn btn-primary btn-sm" %>
    </div>

    <h4 class="comments_title">
      <%= @link.comments.count %> Comments
    </h4>
    <div id="comments">
      <%= render :partial => @link.comments %>
    </div>
    <%= simple_form_for [@link, Comment.new] do |f| %>
      <div class="field">
        <%= f.text_area :body, :required => true, class: "form-control" %>
      </div>
      <br>
      <%= f.submit "Add Comment", class: "btn btn-primary" %>
    <% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

app/views/users/user_profile.html.erb
<p id="notice"><%= notice %></p>
<% if !@user.nil? -%>
<%=
  if !@user.avatar.url.nil?
      image_tag @user.avatar.url(:thumb), class:"img-circle"
    end 
%>


<p>
  <%= @user.name %>
</p>
<% else -%>
  <strong>Not Found</strong>
<% end -%>